"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getDirections = exports.geocodeAddress = exports.onRsvpWrite = exports.onRideAccept = exports.onRideRequest = exports.onEventCreate = exports.selfDeleteAccount = exports.reinstateUser = exports.deactivateUser = exports.onUserStatusChange = exports.onUserPending = exports.approveUser = exports.demoteAdmin = exports.promoteAdmin = exports.onUserCreate = void 0;
const v2_1 = require("firebase-functions/v2");
(0, v2_1.setGlobalOptions)({ region: 'us-central1', maxInstances: 10 });
var onUserCreate_1 = require("./auth/onUserCreate");
Object.defineProperty(exports, "onUserCreate", { enumerable: true, get: function () { return onUserCreate_1.onUserCreate; } });
var promoteAdmin_1 = require("./auth/promoteAdmin");
Object.defineProperty(exports, "promoteAdmin", { enumerable: true, get: function () { return promoteAdmin_1.promoteAdmin; } });
var demoteAdmin_1 = require("./auth/demoteAdmin");
Object.defineProperty(exports, "demoteAdmin", { enumerable: true, get: function () { return demoteAdmin_1.demoteAdmin; } });
var approveUser_1 = require("./approvals/approveUser");
Object.defineProperty(exports, "approveUser", { enumerable: true, get: function () { return approveUser_1.approveUser; } });
var onPendingUser_1 = require("./approvals/onPendingUser");
Object.defineProperty(exports, "onUserPending", { enumerable: true, get: function () { return onPendingUser_1.onUserPending; } });
Object.defineProperty(exports, "onUserStatusChange", { enumerable: true, get: function () { return onPendingUser_1.onUserStatusChange; } });
var deactivate_1 = require("./users/deactivate");
Object.defineProperty(exports, "deactivateUser", { enumerable: true, get: function () { return deactivate_1.deactivateUser; } });
var reinstate_1 = require("./users/reinstate");
Object.defineProperty(exports, "reinstateUser", { enumerable: true, get: function () { return reinstate_1.reinstateUser; } });
var selfDelete_1 = require("./users/selfDelete");
Object.defineProperty(exports, "selfDeleteAccount", { enumerable: true, get: function () { return selfDelete_1.selfDeleteAccount; } });
var onEventCreate_1 = require("./events/onEventCreate");
Object.defineProperty(exports, "onEventCreate", { enumerable: true, get: function () { return onEventCreate_1.onEventCreate; } });
var onRideRequest_1 = require("./rides/onRideRequest");
Object.defineProperty(exports, "onRideRequest", { enumerable: true, get: function () { return onRideRequest_1.onRideRequest; } });
var onRideAccept_1 = require("./rides/onRideAccept");
Object.defineProperty(exports, "onRideAccept", { enumerable: true, get: function () { return onRideAccept_1.onRideAccept; } });
var onRsvpWrite_1 = require("./badges/onRsvpWrite");
Object.defineProperty(exports, "onRsvpWrite", { enumerable: true, get: function () { return onRsvpWrite_1.onRsvpWrite; } });
var geocode_1 = require("./maps/geocode");
Object.defineProperty(exports, "geocodeAddress", { enumerable: true, get: function () { return geocode_1.geocodeAddress; } });
var directions_1 = require("./maps/directions");
Object.defineProperty(exports, "getDirections", { enumerable: true, get: function () { return directions_1.getDirections; } });
//# sourceMappingURL=index.js.map